server:
  port: 8080

logging:
  level:
    com.example.kakao: INFO

kakao:
  auth:
    client: f1c8e34b151607c955acf70fe603169e
    redirect: http://localhost:8080/auth/login/kakao
  api:
    token-uri: https://kauth.kakao.com/oauth/token
    userinfo-uri: https://kapi.kakao.com/v2/user/me
